theme: minima
title: MultiCamCows2024: A testing webpage to be updated
author: Phoenix Yu
description: This webpages is a web interface for dataset, models, and the paper involved in MultiCamCows2024
